services:
  galaxy:
    image: bgruening/galaxy-stable
    ports:
      - 8088:80
      - 8021:21
      - 8022:22
    privileged: false
#    healthcheck:
#      test: ["CMD", "curl", "-fkq", "http://localhost:8010/health.html"]
#      interval: 5s
#      timeout: 5s
#      retries: 3
#    environment: 
#    - CURL_CA_BUNDLE=/shared/cert/ca.crt
    networks:
      - public
      - secure
    volumes:
      - ./export:/export
      - starter-kit-storage-and-interfaces_shared:/shared
    extra_hosts:
      - dockerhost:host-gateway
    environment:
      - ENABLE_TTS_INSTALL=True
      - GALAXY_CONFIG_FILE=/export/config/galaxy.yml

networks:
  public:
    name: starter-kit-htsget_public
  secure:
    name: starter-kit-storage-and-interfaces_secure
    external: true

volumes:
  starter-kit-storage-and-interfaces_shared:
    external: true

